// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd4Zd33EMaDSKJoHuVVK5yCPqjSQZwK94',
    appId: '1:929253381679:web:c9a27f70abd9261e5418da',
    messagingSenderId: '929253381679',
    projectId: 'sproutlings-dc41d',
    authDomain: 'sproutlings-dc41d.firebaseapp.com',
    storageBucket: 'sproutlings-dc41d.appspot.com',
    measurementId: 'G-63BQVVG83J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRJKhpgBBa8Obt6uJbI0Um_gXOBmm3LB0',
    appId: '1:929253381679:android:c4f3dbf5c9ff849d5418da',
    messagingSenderId: '929253381679',
    projectId: 'sproutlings-dc41d',
    storageBucket: 'sproutlings-dc41d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDchOYITK__o4z3U4c8fSVfcXqrdiYez2g',
    appId: '1:929253381679:ios:0cdfc7de28b231ba5418da',
    messagingSenderId: '929253381679',
    projectId: 'sproutlings-dc41d',
    storageBucket: 'sproutlings-dc41d.appspot.com',
    iosBundleId: 'com.example.flutterTm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDchOYITK__o4z3U4c8fSVfcXqrdiYez2g',
    appId: '1:929253381679:ios:0cdfc7de28b231ba5418da',
    messagingSenderId: '929253381679',
    projectId: 'sproutlings-dc41d',
    storageBucket: 'sproutlings-dc41d.appspot.com',
    iosBundleId: 'com.example.flutterTm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd4Zd33EMaDSKJoHuVVK5yCPqjSQZwK94',
    appId: '1:929253381679:web:c8aceafae628e2065418da',
    messagingSenderId: '929253381679',
    projectId: 'sproutlings-dc41d',
    authDomain: 'sproutlings-dc41d.firebaseapp.com',
    storageBucket: 'sproutlings-dc41d.appspot.com',
    measurementId: 'G-WKPX7JQTWF',
  );
}
